config/routes.rb
Rails.application.routes.draw do
  root 'events#index'

  resources :events, only: [:index,:show]
  get 'about' => "events#about", as: :about

end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :speakers, dependent: :destroy
  # attr_accessible :day, :time, :title, :image, :large_image

  scope :first_day, ->() {where(:day=>Date.new(2014, 4, 25)).order(:time)}
  scope :second_day, ->() {where(:day=>Date.new(2014, 4, 26)).order(:time)}

  def first_day?
  	self.day == Date.new(2014, 4, 25)
  end
  def second_day?
  	self.day == Date.new(2014, 4, 26)
  end

  def day_class
    if self.first_day?
      'first_day_show'
    else
      'second_day_show'
    end
  end

end

app/models/speaker.rb
class Speaker < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.order(:day).order(:time)

    if params[:format] == 'json'
      render layout: false
    end
  end

  def show
    @event = Event.find(params['id'])
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/events/about.slim
.app.about_page
  header.header
    span.header__arrow_left
      = link_to events_path do
        |voltar
    .header__brand
      = link_to root_path do
        h1 BRAPPS


  section.container
    .about
      h1
        |Quer aprender a desenvolver uma App como essa?
      h3
        |Venha conhecer o stand da <b><a href='http://www.superquadra.co' target='_blank'>Superquadra</a></b> no evento do BRAPPS e aprenda design e programação em poucos minutos.
    .team_image
      = link_to 'http://www.superquadra.co', target: '_blank' do
        = image_tag('team-superquadra.jpg')

app/views/events/index.slim
.app.has-navbar
  header.header
    span.header__info
      = link_to about_path do
        |info
    .header__brand
      = link_to root_path do
        h1 BRAPPS
  nav.nav
    ul
      li.nav__item.nav__item--day1
        = link_to '#', data: {tab: 'tab-1'} do
          | Sexta Feira <span>25 de abril</span>
      li.nav__item.nav__item--day2
        = link_to '#', data: {tab: 'tab-2'}, class: 'is-active' do
          | Sábado <span>26 de abril</span>

  section.container
    .list.list--day1 data-tab-content='tab-1'
      - @events.first_day.each do |event|
        .list__item
          = link_to(event) do
            .item__image
              = image_tag event.image
            .body
              .item__meta
                = event.time
              .item__title
                = event.title

    .list.list--day2.is-active data-tab-content='tab-2'
      - @events.second_day.each do |event|
        .list__item
          = link_to(event) do
            .item__image
              = image_tag event.image
            .body
              .item__meta
                = event.time
              .item__title
                = event.title

app/views/events/show.slim
- @title = "#{@event.title}"

div class="app #{@event.day_class}"
  header.header
    span.header__arrow_left
      = link_to events_path do
        |voltar
    span.header__info
      = link_to about_path do
        |info
    .header__brand
      = link_to root_path do
        h1 BRAPPS


  section.container
    .event
      .event__image
        = image_tag @event.large_image
      .time
        - if @event.first_day?
          |Sexta, &nbsp;
          =@event.time
        - else
          |Sábado, &nbsp;
          =@event.time
      .event__title
        = @event.title


      .event__speakers
        - @event.speakers.each do |speaker|
          span.speakers__name
            = speaker.name
          span.spealers_company
            |, &nbsp;
            = speaker.company
          br

app/views/layouts/application.slim
/!
  Aprenda a ver como designer, agir como empreendedor e programar like a boss - www.superquadra.co
doctype 5
html lang='#{I18n.locale}'
  head
    meta charset='utf-8'
    - if @title.present?
      title #{@title} — BRAPPS
    - else
      title BRAPPS
    - if @description.present?
      meta name='description' content='#{@description}'
    - else
      meta name='description' content=''
    meta name='HandheldFriendly' content='True'
    meta name='MobileOptimized' content='320'
    meta http-equiv='cleartype' content='on'
    meta name='viewport' content='initial-scale=1.0,user-scalable=no,maximum-scale=1,width=device-width'
    meta name='viewport' content='initial-scale=1.0,user-scalable=no,maximum-scale=1' media='(device-height: 568px)'
    meta name="apple-itunes-app" content="app-id=866641424"

    / ICON
    = favicon_link_tag 'app-icons/AppIcon57x57.png', rel: 'shortcut icon', :type => 'image/png'
    / iPhone
    = favicon_link_tag 'app-icons/AppIcon57x57.png', sizes: '57x57', rel: 'apple-touch-icon-precomposed', type: 'image/png'
    / iPhone (retina) - Icon
    = favicon_link_tag 'app-icons/AppIcon72x72_2x.png', sizes: '144x144', rel: 'apple-touch-icon-precomposed', type: 'image/png'
    / Ipad - Icon
    = favicon_link_tag 'app-icons/AppIcon72x72.png', sizes: '72x72', rel: 'apple-touch-icon-precomposed', type: 'image/png'
    / Ipad (retina) - Icon
    = favicon_link_tag 'app-icons/AppIcon57x57_2x.png', sizes: '114x114', rel: 'apple-touch-icon-precomposed', type: 'image/png'

    / SPLASH
    // iOS 6 & 7 iPhone 5
    link href="#{{asset_path('app-startup/splash-iphone5.png')}}" media="(device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2)" rel="apple-touch-startup-image"
    // iOS 6 & 7 iPhone (retina)
    link href="#{{asset_path('app-startup/splash-iphone4.png')}}" media="(device-width: 320px) and (device-height: 480px) and (-webkit-device-pixel-ratio: 2)" rel="apple-touch-startup-image"
    // iOS 6 iPhone
    link href="#{{asset_path('app-startup/splash-iphone.png')}}" media="(device-width: 320px) and (device-height: 480px) and (-webkit-device-pixel-ratio: 1)" rel="apple-touch-startup-image"

    / For iOS web apps. Delete if not needed. https://github.com/h5bp/mobile-boilerplate/issues/94
    meta name='apple-mobile-web-app-capable' content='yes'
    meta name='apple-mobile-web-app-status-bar-style' content='black-translucent'
    meta name='apple-mobile-web-app-title' content='BRAPPS'
    / Tile icon for Win8 (144x144 + tile color)
    meta name='msapplication-TileImage' content='#{{asset_path('app-icons/AppIcon72x72_2x.png')}}'
    meta name='msapplication-TileColor' content='#89ddc3'
    meta name='author' content='Startaê — http://www.startae.com.br'
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all'

  body class='#{@page_class} #{@item_menu}'
    = yield
    = javascript_include_tag 'vendor'
    = javascript_include_tag 'application'
    = render 'partials/development' if Rails.env.development?

    javascript:
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
      ga('create', 'UA-50372726-1', 'agendabrapps.com');
      ga('send', 'pageview');

app/views/partials/_development.slim
javascript:
  document.write('<script src="http://' + (location.host || 'localhost').split(':')[0] + ':35729/livereload.js?snipver=1"></' + 'script>')